kind: MLApp
metadata:
  name: cntk
spec:
  package_manager: "pip{{.python_version.value}}"
  packages:
    - names:
      {{- range $i, $value := .packages }}
      - "{{ $value }}"
      {{- end }}
      manager: "pip{{.python_version.value}}"
  tasks:
  - name: prepare-data
    resources:
    - name: upload
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 1
      allowFail: true
      images:
        cpu: busybox
      command: "echo \"Uploading Data\";echo \"Done!!!\""
      workdir: "$DATA_DIR"
      env:
      - name: PYTHONPATH
        value: /cntk/bindings/python:/usr/local
      - name: KERAS_BACKEND
        value: cntk
      volumes:
      - name: data
  - name: standalone
    resources:
    - name: worker
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 0
      allowFail: true
      {{- if eq .python_version.value "3" }}
      images:
        gpu: "kuberlab/mlboard-jupyter-cntk:{{.cntk_version.value}}-gpu-python3.5-cuda8.0-cudnn6.0"
        cpu: "kuberlab/mlboard-jupyter-cntk:{{.cntk_version.value}}-cpu-python3.5"
      {{- end }}
      {{- if eq .python_version.value "2" }}
      images:
        gpu: "kuberlab/mlboard-jupyter-cntk:{{.cntk_version.value}}-gpu-python2.7-cuda8.0-cudnn6.0"
        cpu: "kuberlab/mlboard-jupyter-cntk:{{.cntk_version.value}}-cpu-python2.7"
      {{- end }}
      command: "source /cntk/activate-cntk; python hello.py"
      env:
      - name: PYTHONPATH
        value: /cntk/bindings/python:/usr/local
      - name: KERAS_BACKEND
        value: cntk
      workdir: "$SRC_DIR"
      resources:
        accelerators:
          gpu: 0
        requests:
          cpu: 100m
          memory: 64Mo
        limits:
          cpu: 1000m
          memory: 4Gi
      default_volume_mapping: true
  uix:
  - name: jupyter
    displayName: Jupyter
    {{- if eq .python_version.value "3"}}
    images:
        gpu: "kuberlab/mlboard-jupyter-cntk:{{.cntk_version.value}}-gpu-python3.5-cuda8.0-cudnn6.0"
        cpu: "kuberlab/mlboard-jupyter-cntk:{{.cntk_version.value}}-cpu-python3.5"
    {{- end }}
    {{- if eq .python_version.value "2"}}
    images:
        gpu: "kuberlab/mlboard-jupyter-cntk:{{.cntk_version.value}}-gpu-python2.7-cuda8.0-cudnn6.0"
        cpu: "kuberlab/mlboard-jupyter-cntk:{{.cntk_version.value}}-cpu-python2.7"
    {{- end }}
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 1000m
        memory: 4Gi
    env:
    - name: PYTHONPATH
      value: /cntk/bindings/python:/usr/local
    - name: KERAS_BACKEND
      value: cntk
    ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
    default_volume_mapping: true
  serving:
  - name: serving
    displayName: Serving
    {{- if eq .python_version.value "3"}}
    images:
        gpu: "kuberlab/mlboard-jupyter-cntk:{{.cntk_version.value}}-gpu-python3.5-cuda8.0-cudnn6.0"
        cpu: "kuberlab/mlboard-jupyter-cntk:{{.cntk_version.value}}-cpu-python3.5"
    {{- end }}
    {{- if eq .python_version.value "2"}}
    images:
        gpu: "kuberlab/mlboard-jupyter-cntk:{{.cntk_version.value}}-gpu-python2.7-cuda8.0-cudnn6.0"
        cpu: "kuberlab/mlboard-jupyter-cntk:{{.cntk_version.value}}-cpu-python2.7"
    {{- end }}
    workdir: "$SRC_DIR"
    env:
    - name: PYTHONPATH
      value: /cntk/bindings/python:/usr/local
    - name: KERAS_BACKEND
      value: cntk
    command: "source /cntk/activate-cntk; python hello.py"
    resources:
      accelerators:
        gpu: 0
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 1000m
        memory: 4Gi
    ports:
    - port: {{ .serving_port }}
      targetPort: {{ .serving_port }}
      protocol: TCP
      name: http
    default_volume_mapping: true
  volumes:
  - isLibDir: false
    mountPath: /notebooks/training
    name: training
    clusterStorage: {{ .storage.value }}
    subPath: training
  - gitRepo:
      repository: https://github.com/kuberlab-catalog/cntk
    isLibDir: false
    mountPath: /notebooks/src
    name: src
    subPath: cntk/src
  - isLibDir: true
    mountPath: /notebooks/lib
    name: lib
    clusterStorage: {{ .storage.value }}
    subPath: lib
  - isLibDir: false
    mountPath: /notebooks/data
    name: data
    clusterStorage: {{ .storage.value }}
    subPath: {{ .data_path }}
  - isLibDir: false
    mountPath: /notebooks
    name: code
    subPath: code
    clusterStorage: {{ .storage.value }}
